# conf/config.yaml - Original config for LINEAR DiBS
hydra:
  job_logging:
    formatters:
      ultra_short:
        format: '[%(asctime)s][%(name).1s][%(levelname).1s] %(message)s'
        datefmt: '%H:%M:%S'
    handlers:
      console:
        formatter: ultra_short
      file:
        formatter: ultra_short

defaults:
  - override hydra/job_logging: default

# General experiment parameters
project_name: "dibs_torch_v2_experiment"
experiment_name: "x1_x2_x3_ground_truth"
seed: 100

# Data generation parameters
data:
  d_nodes: 3
  num_samples: 500
  synthetic_obs_noise_std: 0.1
  ground_truth_seed: 100

# Particle initialization
particle:
  k_latent: 3
  init_seed_offset: 1

# DiBS Model Hyperparameters (original for LINEAR)
model_hparams:
  alpha_val: 0.1
  beta_val: 1.0
  tau_val: 1.0
  sigma_z_val_divisor_for_k_latent: 1.0
  sigma_obs_noise_val_is_data_noise: true
  rho_val: 0.05
  temp_ratio_val: 0.0
  n_grad_mc_samples_val: 5
  n_nongrad_mc_samples_val: 10
  theta_prior_sigma_val: 0.5

# Training/Optimization parameters (original for LINEAR)
training:
  lr_z: 0.005
  lr_theta: 0.005
  num_iterations: 2000
  max_grad_norm_z: 11.0
  max_grad_norm_theta: 19.0

# Default device
device: 'cpu'